version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Порт фронтенда
      - "3000:3000" # Порт бэкенда
    networks:
      - vstk-network

networks:
  vstk-network:
    driver: bridge
